swagger: '2.0'
info:
  title: Pet API
  description: Access, add and update the info of your favourite pets.
  version: "1.0.0"
# the domain of the service
host: localhost:5000
schemes:
  - http
# will be prefixed to all paths
basePath: /
produces:
  - application/json

paths:
  /list:
    get:
      summary: Pet Types
      description: |
        The list endpoint returns a JSON of pets.
      tags:
        - Pets
      responses:
        200:
          description: A JSON of pets.
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /add:
    post:
      summary: Add pet to database collection
      description: |
        The list endpoint returns a JSON of pets.
      parameters:
        - name: name
          in: query
          description: Pet's name
          required: true
          type: number
          format: double
        - name: species
          in: query
          description: Pet's species
          required: true
          type: number
          format: double
        - name: gender
          in: query
          description: Pet's gender
          required: true
          type: number
          format: double
        - name: birthday
          in: query
          description: Pet's birthday
          required: true
          type: number
          format: double
      tags:
        - Pets
      responses:
        201:
          description: JSON response
          schema:
            type: array
            items:
              $ref: '#/definitions/Res'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

  /update:
    post:
      summary: Update pet entry
      description: |
        Updates pet entry in the pets schema by ID.
      parameters:
        - name: id
          in: query
          description: Pet's ID
          required: true
          type: number
          format: integer
        - name: name
          in: query
          description: Pet's name
          required: true
          type: string
        - name: species
          in: query
          description: Pet's species
          required: true
          type: string
        - name: gender
          in: query
          description: Pet's gender
          required: true
          type: string
      tags:
        - Pets
      responses:
        201:
          description: JSON response
          schema:
            type: array
            items:
              $ref: '#/definitions/Res'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Pet:
    type: object
    properties:
      id:
        type: integer
        description: Unique identifier representing a specific pet.
      name:
        type: string
        description: Pet's name.
      species:
        type: string
        description: Pet's species.
      gender:
        type: string
        description: Pet's gender
      birthday:
        type: object
        description: Pet's birthday date object.
  Res:
    type: object
    properties:
      success:
        type: string
        description: Result of the query

  Error:
    type: object
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string
